# Generated by Django 5.0.4 on 2024-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='f_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='l_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_link',
            field=models.URLField(null=True),
        ),
    ]
